language: python
python:
    - 2.7
    - 3.4
    - 3.5
install:
    - pip install -U .
    - pip install flake8 hacking
script:
    - flake8
    - python setup.py test
    - cd example && rime help && rime test && rime clean
notifications:
    email:
        on_success: never
        on_failure: never
