language: python
python:
    - 2.7
install:
    - pip install -U .
    - pip install flake8 hacking
script:
    - flake8
    - python setup.py test
    - cd example && rime test
notifications:
    email:
        on_success: never
        on_failure: never
